# Generated by Django 3.2.9 on 2021-12-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term')], max_length=20)),
                ('details', models.TextField(default='')),
                ('target', models.IntegerField(default=0)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
    ]
