# Generated by Django 3.2.9 on 2021-12-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='pictures',
            field=models.ImageField(default=1, upload_to='fundings/'),
            preserve_default=False,
        ),
    ]
