# Generated by Django 3.2.9 on 2021-12-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_funding_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='pictures',
            new_name='image',
        ),
    ]
