# Generated by Django 3.0.7 on 2021-12-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_auto_20211202_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='current_donation',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='rating',
        ),
    ]
