# Generated by Django 3.2.9 on 2021-12-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_rename_pictures_funding_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='end',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='start',
        ),
        migrations.AddField(
            model_name='funding',
            name='commentinitial',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='current_donation',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding')),
            ],
        ),
    ]
