# Generated by Django 3.2.9 on 2021-12-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('upassword', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
